repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use latest stable version
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
